# Generated by Django 5.0.1 on 2024-04-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorites",
            field=models.ManyToManyField(blank=True, null=True, to="app.user"),
        ),
    ]
